[package]
name = "vapurr-wallet"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "account abstraction and session keys for vapurr"

[dependencies]
bip39.workspace = true
hex.workspace = true
hmac.workspace = true
k256.workspace = true
sha2.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
thiserror.workspace = true
vapurr-id.workspace = true
vapurr-rhc.workspace = true
zeroize.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_Storage_FileSystem"] }
